#!/bin/sh
now="$(date +%Y%m%d_%H%M%S)"
#fast path
ssh deploy@159.203.239.186 <<EOF
  cd /opt/epicvisor-app
  git pull
  npm prune
  npm install
  cp /opt/.env /opt/epicvisor-app
EOF

workdir=epicvisor_$now

#better path
# ssh deploy@159.203.239.186 <<EOF
#   cd /opt/
#   git clone git@bitbucket.org:epicvisor/epicvisor-app.git $workdir && cd $workdir
#   printf "Cloned EpicVisor App created directory $workdir"
#   cp /opt/.env /opt/$workdir
#   printf "copying .env to $workdir"
#   npm install
# EOF
